#-------------------------------
# General Site Settings

title: Javier Velazquez Traut
description: Personal portfolio
email: j.velazqueztraut@gmail.com

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Javier Velazquez Traut Personal portfolio'
  rel-author: 'http://j.velazqueztraut.com'
  rel-publisher: 'http://j.velazqueztraut.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  This is a personal portfolio theme that I built from the ground up, using the [DevTips Starter Kit](http://devtipsstarterkit.com/) as a foundation for starting, and following closely the amazing tutorial by [Travis Neilson over at DevTips](https://www.youtube.com/watch?v=T6jKLsxbFg4&list=PL0CB3OvPhDA_STygmp3sDenx3UpdOMk7P). You can [check out the demo](lenpaul.github.io/portfolio-jekyll-theme/), and [fork the repository](https://github.com/LeNPaul/portfolio-jekyll-theme/fork), to get started.

contact: >
  # Contact

  You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Videowall', folder: 'proj-16-Videowall'}
- {name: 'Ligth show', folder: 'proj-15-VEEM'}
- {name: 'Museo Malvinas', folder: 'proj-5-Malvinas'}
- {name: 'Orquesta Digital', folder: 'proj-1-Orquesta'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'jvelazqueztraut'}
- {icon: 'github', link: 'jvelazqueztraut'}
- {icon: 'facebook', link: 'jvelazqueztraut'}
- {icon: 'instagram', link: 'nigrou'}
- {icon: 'twitter', link: 'nigrou'}
- {icon: 'envelope', link: 'mailto:j.velazqueztraut@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
