#-------------------------------
# General Site Settings

title: Javier Velazquez Traut
subtitle: Lateral Portfolio
description: Javier Velazquez Traut Portfolio
email: j.velazqueztraut@gmail.com

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Javier Velazquez Traut Portfolio Creative Technologist Electronic Engineer Cran.io Cranio +Otros Masotros openFrameworks'
  rel-author: 'http://j.velazqueztraut.com'
  rel-publisher: 'http://j.velazqueztraut.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-104060517-1'

#-------------------------------
# Work Section

projects:
- {title: 'Videowall', name: 'videowall-A3', date: 'May 2017'}
- {title: 'Super LED Tubes', name: 'VEEM', date: 'March 2017'}
- {title: 'Autocalibration System', name: 'autocalibration', date: 'Sept 2014'}
- {title: 'Museo Malvinas', name: 'malvinas', date: 'June 2014'}
- {title: 'Art Drums', name: 'art-drums', date: 'May 2014'}
- {title: 'Kinder World', name: 'kinder', date: 'July 2013'}
- {title: 'Augmented Professionals', name: 'min-social', date: 'Oct 2012'}
- {title: 'Digital Orchestra', name: 'orquesta-digital', date: 'July 2012'}
- {title: 'Live Kinect Visuals', name: 'fuga', date: 'May 2012'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jvelazqueztraut'}
- {icon: 'github', link: 'https://github.com/jvelazqueztraut'}
- {icon: 'facebook', link: 'https://www.facebook.com/jvelazqueztraut'}
- {icon: 'instagram', link: 'https://www.instagram.com/nigrou'}
- {icon: 'twitter', link: 'https://twitter.com/nigrou'}
- {icon: 'envelope', link: 'mailto:j.velazqueztraut@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
