#-------------------------------
# General Site Settings

title: Javier Velazquez Traut
subtitle: Portfolio
description: Javier Velazquez Traut Portfolio
email: j.velazqueztraut@gmail.com

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'blog.html'}
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Javier Velazquez Traut Portfolio Creative Technologist Electronic Engineer Virtual Augmented Mixed Reality Developer Visual Artist openFrameworks Touchdesigner Unity'
  rel-author: 'http://velazqueztraut.com'
  rel-publisher: 'http://velazqueztraut.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-104060517-1'

#-------------------------------
# Work Section

projects:
- {title: 'Persiana', name: 'persiana', date: 'Apr 2024'}
- {title: 'BOTB', name: 'botb', date: 'Oct 2023'}
- {title: 'YMIYP VR', name: 'ymiypvr', date: 'Apr 2023'}
- {title: 'Your Mind is Your Playground', name: 'ymiyp', date: 'Oct 2022'}
- {title: 'GERDA Live Set', name: 'goodenough', date: 'Sep 2022'}
- {title: 'London Craftweek Fashion Show', name: 'lcw', date: 'May 2022'}
- {title: 'Unusual Party Sign', name: 'unusual', date: 'Oct 2021'}
- {title: 'A3 Videowall', name: 'videowall-A3', date: 'May 2017'}
- {title: 'Super LED Tubes', name: 'VEEM', date: 'March 2017'}
- {title: 'Betrack IoT', name: 'betrack', date: 'Dec 2016'}
- {title: 'YPF Interactive Semi-truck', name: 'trailer', date: 'Sept 2014'}
- {title: 'Autocalibration System', name: 'autocalibration', date: 'Aug 2014'}
- {title: 'Museo Malvinas', name: 'malvinas', date: 'June 2014'}
- {title: 'Personal Art Drums', name: 'art-drums', date: 'May 2014'}
- {title: 'Mecon Tecnópolis 2013', name: 'tecno-2013', date: 'July 2013'}
- {title: 'Kinder World', name: 'kinder', date: 'July 2013'}
- {title: 'Augmented Professionals', name: 'min-social', date: 'Oct 2012'}
- {title: 'Tecnópolis Digital Orchestra', name: 'orquesta-digital', date: 'July 2012'}
- {title: 'CETC Live Kinect Visuals', name: 'fuga', date: 'May 2012'}
- {title: 'Interactive Phrases', name: 'lengua', date: 'Sept 2011'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jvelazqueztraut'}
- {icon: 'github', link: 'https://github.com/jvelazqueztraut'}
- {icon: 'facebook', link: 'https://www.facebook.com/jvelazqueztraut'}
- {icon: 'instagram', link: 'https://www.instagram.com/eljavote'}
- {icon: 'twitter', link: 'https://twitter.com/eljavote'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
